FROM platformatic/node-caged:26-alpine AS base

FROM base AS dependencies

WORKDIR /app

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat && \
  npm install -g corepack

# Copy package-related files first to leverage Docker's caching mechanism
COPY package.json package-lock.json* .npmrc* yarn.lock* pnpm-lock.yaml* pnpm-workspace.yaml ./

# Install project dependencies with frozen lockfile for reproducible builds
RUN --mount=type=cache,target=/root/.npm \
  --mount=type=cache,target=/usr/local/share/.cache/yarn \
  --mount=type=cache,target=/root/.local/share/pnpm/store \
  if [ -f package-lock.json ]; then \
    npm ci --no-audit --no-fund; \
  elif [ -f yarn.lock ]; then \
    corepack enable yarn && yarn install --frozen-lockfile --production=false && yarn cache clean; \
  elif [ -f pnpm-lock.yaml ]; then \
    corepack enable pnpm && pnpm install --frozen-lockfile; \
  else \
    echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

ARG S3_URL
ENV S3_URL=$S3_URL

ENV NEXT_TELEMETRY_DISABLED=1
ENV CI=1

WORKDIR /app

RUN npm install -g corepack

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

# Build Next.js application
RUN --mount=type=cache,target=/app/.next/cache \
  if [ -f package-lock.json ]; then \
    npm run build; \
  elif [ -f yarn.lock ]; then \
    corepack enable yarn && yarn build; \
  elif [ -f pnpm-lock.yaml ]; then \
    corepack enable pnpm && pnpm build; \
  else \
    echo "Lockfile not found." && exit 1; \
  fi

FROM base AS runner

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

RUN apk add --no-cache curl && \
  addgroup --system --gid 1001 nextjs && \
  adduser --system --uid 1001 --ingroup nextjs nextjs && \
  mkdir .next && \
  chown nextjs:nextjs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nextjs /app/public ./public
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 CMD [ "curl", "-f", "http://localhost:3000/api/health" ]

ENTRYPOINT [ "node", "server.js" ]
