services:
  mongodb:
    image: mongo:8-noble
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: format
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping").ok' --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "7000:7000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 7000
      KC_HEALTH_ENABLED: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/format?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mongodb-data:
