FROM bellsoft/liberica-runtime-container:jdk-25-slim-glibc AS builder

ENV SPRING_PROFILES_ACTIVE=prod

WORKDIR /app

COPY gradle gradle
COPY gradlew build.gradle.kts settings.gradle.kts ./

RUN chmod u+x ./gradlew && ./gradlew dependencies --no-daemon

COPY . .

RUN ./gradlew --no-daemon clean bootJar -Paot && \
    mv build/libs/*.jar app.jar && \
    java -Djarmode=tools -jar app.jar extract --layers --destination extracted

FROM bellsoft/liberica-runtime-container:jre-25-cds-glibc

ENV SPRING_PROFILES_ACTIVE=prod

WORKDIR /app

RUN apk --no-cache add curl && \
    addgroup --system spring && \
    adduser --system --disabled-password --ingroup spring spring

COPY --from=builder --chown=spring /app/extracted/dependencies/ ./
COPY --from=builder --chown=spring /app/extracted/spring-boot-loader/ ./
COPY --from=builder --chown=spring /app/extracted/snapshot-dependencies/ ./
COPY --from=builder --chown=spring /app/extracted/application/ ./

USER spring

EXPOSE 8080

ENTRYPOINT ["java", "-XX:+UseZGC", "-XX:+UseCompactObjectHeaders", "-Dspring.aot.enabled=true", "-jar", "app.jar"]
