import { FormStatus, Language } from "@/core/types/form-detail-response-dto";
import { FormListResponseDto } from "@/core/types/form-list-response-dto";

export const placeholder_image_url =
  "https://media.gettyimages.com/id/2160237234/video/grass-waving-in-the-wind-sunny-day-in-the-forest.jpg?s=640x640&k=20&c=A5Fkny7OIkrfeouSyoUZ_m9vn0QkJd9oTv4Scs4iOfU=";

// placeholder data, to be replaced with data from backend
export const forms: FormListResponseDto[] = [
  {
    id: "1",
    name: "Quiz o kotach",
    slug: "quiz-o-kotach",
    description: "Krótki quiz sprawdzający wiedzę o kotach.",
    language: Language.Pl,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail:
      "https://media.istockphoto.com/id/1038870630/photo/woman-standing-and-looking-at-lago-di-carezza-in-dolomites.jpg?s=612x612&w=0&k=20&c=sRbpFCJ-odpl2cQetrZaxlxL0oqAmxcjDEGN46kmGJ0=",
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    submissionsCount: 34,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2021-10-25").toISOString(),
    updatedAt: new Date("2021-10-25").toISOString(),
  },
  {
    id: "2",
    name: "Customer Satisfaction Survey",
    slug: "customer-satisfaction-survey",
    description:
      "A very long description that goes into detail about the purpose of the customer satisfaction survey form, its intended audience, and the types of questions that will be included to gather comprehensive feedback from customers regarding their experiences with our products and services.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail:
      "https://img.freepik.com/free-photo/morskie-oko-tatry_1204-510.jpg?semt=ais_hybrid&w=740&q=80",
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: false,
    saveSubmissions: true,
    submissionsCount: 0,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2023-09-23").toISOString(),
    updatedAt: new Date("2023-09-23").toISOString(),
  },
  {
    id: "3",
    name: "Event Feedback Form",
    slug: "event-feedback-form",
    description: "Collect feedback from event attendees.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail: placeholder_image_url,
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    submissionsCount: 12,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2023-08-02").toISOString(),
    updatedAt: new Date("2023-08-02").toISOString(),
  },
  {
    id: "4",
    name: "Website Usability Survey",
    slug: "website-usability-survey",
    description: "Feedback form for website usability studies.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail:
      "https://img.freepik.com/free-photo/beautiful-landscape-mountains-lake_74190-14081.jpg?w=740&t=st=1698247201~exp=1698247801~hmac=3f3f3f6f4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e",
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: false,
    saveSubmissions: true,
    submissionsCount: 36,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2025-07-30").toISOString(),
    updatedAt: new Date("2025-07-30").toISOString(),
  },
  {
    id: "5",
    name: "Product Order Form",
    slug: "product-order-form",
    description: "Form to place product orders online.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail: placeholder_image_url,
    allowsQuestionsPreview: false,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    submissionsCount: 0,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2023-12-12").toISOString(),
    updatedAt: new Date("2023-12-12").toISOString(),
  },
  {
    id: "6",
    name: "Employee Satisfaction Survey",
    slug: "employee-satisfaction-survey",
    description: "A survey to assess employee satisfaction within the company.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail: placeholder_image_url,
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: false,
    saveSubmissions: true,
    submissionsCount: 1,
    questionsCount: 0,

    authorName: "Jan Kowalski",
    createdAt: new Date("2018-05-01").toISOString(),
    updatedAt: new Date("2018-05-01").toISOString(),
  },
  {
    id: "7",
    name: "Market Research Questionnaire",
    slug: "market-research-questionnaire",
    description: "A questionnaire to gather market research data.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail: placeholder_image_url,
    allowsQuestionsPreview: false,
    allowsGuestSubmissions: false,
    saveSubmissions: true,
    submissionsCount: 50,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2023-03-15").toISOString(),
    updatedAt: new Date("2023-03-15").toISOString(),
  },
  {
    id: "8",
    name: "Event Registration Form",
    slug: "event-registration-form",
    description: "Form for registering attendees for events.",
    language: Language.En,
    status: FormStatus.Public,
    estimatedDuration: "PT5M",
    thumbnail: placeholder_image_url,
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    submissionsCount: 0,
    questionsCount: 0,
    authorName: "Jan Kowalski",
    createdAt: new Date("2023-02-28").toISOString(),
    updatedAt: new Date("2023-02-28").toISOString(),
  },
];
