FROM node:26-alpine AS theme-builder

WORKDIR /theme

ENV CI=true

RUN apk add --no-cache maven && \
    npm install -g corepack && \
    corepack enable pnpm

COPY keycloak-theme/ .

RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile && \
    pnpm build-keycloak-theme

FROM quay.io/keycloak/keycloak:26.7

COPY --from=theme-builder /theme/dist_keycloak/theme.jar /opt/keycloak/providers/

COPY config-dev.json /opt/keycloak/data/import/

CMD [ "start-dev", "--import-realm" ]
