import {
  Check,
  ClipboardPen,
  ClipboardPlus,
  Globe,
  Home,
  LayoutGrid,
  List,
  LogIn,
  LogOut,
  Menu,
  Moon,
  Sun,
  User,
  X,
  BadgeQuestionMark,
  ChevronDown,
  ClockArrowUp,
  CornerUpLeft,
  FileKey2,
  HatGlasses,
  LayoutGrid,
  List,
  ListChecks,
  MoreHorizontal,
  PersonStanding,
} from "lucide-react";

export const ICONS = {
  list: List,
  grid: LayoutGrid,
  home: Home,
  form: ClipboardPen,
  formNew: ClipboardPlus,
  user: User,
  lang: Globe,
  check: Check,
  logout: LogOut,
  login: LogIn,
  darkMode: Moon,
  lightMode: Sun,
  menu: Menu,
  close: X,
  back: CornerUpLeft,
  more: MoreHorizontal,
  fillForm: ListChecks,
  anonymous: HatGlasses,
  expandDown: ChevronDown,
  questionsCount: BadgeQuestionMark,
  submissionsCount: PersonStanding,
  estimatedDuration: ClockArrowUp,
  privateForm: FileKey2,
};
