import {
  BadgeQuestionMark,
  Check,
  ChevronDown,
  ChevronUp,
  ClipboardPen,
  ClipboardPlus,
  ClockArrowUp,
  CornerUpLeft,
  FileKey2,
  Globe,
  HatGlasses,
  Home,
  LayoutGrid,
  List,
  ListChecks,
  LogIn,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  PersonStanding,
  SendHorizonal,
  Sun,
  ThumbsDown,
  ThumbsUp,
  User,
  X,
} from "lucide-react";

export const ICONS = {
  list: List,
  grid: LayoutGrid,
  home: Home,
  form: ClipboardPen,
  formNew: ClipboardPlus,
  user: User,
  lang: Globe,
  check: Check,
  logout: LogOut,
  login: LogIn,
  darkMode: Moon,
  lightMode: Sun,
  menu: Menu,
  close: X,
  back: CornerUpLeft,
  more: MoreHorizontal,
  fillForm: ListChecks,
  anonymous: HatGlasses,
  expandDown: ChevronDown,
  questionsCount: BadgeQuestionMark,
  submissionsCount: PersonStanding,
  estimatedDuration: ClockArrowUp,
  privateForm: FileKey2,
  scrollToTop: ChevronUp,
  send: SendHorizonal,
  like: ThumbsUp,
  dislike: ThumbsDown,
} as const;
