import {
  BadgeQuestionMark,
  ChevronDown,
  ChevronUp,
  ClockArrowUp,
  CornerUpLeft,
  HatGlasses,
  LayoutGrid,
  List,
  ListChecks,
  Lock,
  MessageSquareX,
  MoreHorizontal,
  PersonStanding,
} from "lucide-react";

export const ICONS = {
  list: List,
  grid: LayoutGrid,
  back: CornerUpLeft,
  more: MoreHorizontal,
  listChecks: ListChecks,
  hatGlasses: HatGlasses,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  questionsCount: BadgeQuestionMark,
  submissionsCount: PersonStanding,
  estimatedDuration: ClockArrowUp,
  allowGuestSubmissions: Lock,
  noQuestions: MessageSquareX,
};
