spring:
  application:
    name: backend

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50

    mongodb:
      connect-timeout: 20_000
      socket-timeout: 20_000
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

server:
  error:
    include-message: always
    include-path: never

cors:
  allowed-headers: "*"
  allowed-methods: "*"
