spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7001/realms/form-at
          jwk-set-uri: http://keycloak:7001/realms/form-at/protocol/openid-connect/certs
          audiences: ["spring-boot-backend"]

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

logging:
  level:
    root: error
