spring:
  mongodb:
    uri: mongodb://root:password@mongodb:27017/format?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=30000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/form-at
          jwk-set-uri: http://keycloak:7000/realms/form-at/protocol/openid-connect/certs
          audiences: ["spring-boot-backend"]

logging:
  level:
    root: error

s3:
  url: http://rustfs:9000
  region: eu-central-1
  access-key: rustfsadmin
  secret-key: rustfsadmin
  bucket: uploads
