spring:
  mongodb:
    uri: mongodb://root:password@mongodb:27017/format?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=30000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/form-at
          jwk-set-uri: http://keycloak:7000/realms/form-at/protocol/openid-connect/certs
          audiences: ["spring-boot-backend"]

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

logging:
  level:
    root: error

minio:
  endpoint: http://minio:9000
  access-key: root
  secret-key: password
  bucket-name: uploads
