spring:
  application:
    name: format-backend

  mvc:
    problemdetails:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50
        serialization-mode: via_dto

    mongodb:
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  threads:
    virtual:
      enabled: true

  profiles:
    default: dev

cors:
  allowed-headers: "*"
  allowed-methods: "*"
