spring:
  mongodb:
    uri: mongodb://root:password@mongodb:27017/format?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=30000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/form-at
          jwk-set-uri: http://keycloak:7000/realms/form-at/protocol/openid-connect/certs
          audiences: ["spring-boot-backend"]

logging:
  level:
    data: debug
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
            repository:
              query: debug
      mongodb:
        driver:
          protocol:
            command: debug

cors:
  allowed-origins: "*"

s3:
  url: http://rustfs:9000
  force-path-style: true
  region: us-east-1
  access-key: rustfsadmin
  secret-key: rustfsadmin
  bucket: uploads
