spring:
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/format?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/form-at
          jwk-set-uri: http://keycloak:7000/realms/form-at/protocol/openid-connect/certs
          audiences: ["spring-boot-backend"]

logging:
  level:
    data: debug
    org:
      springframework:
        security:
          oauth2: debug
        data:
          mongodb:
            core:
              MongoTemplate: debug
            repository:
              query: debug

springdoc:
  api-docs:
    path: /api/docs

  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: "*"
