import { FormListResponseDto } from "@/core/types/form";

export const userExampleForms: FormListResponseDto[] = [
  {
    id: "1",
    name: "Cat Quiz",
    slug: "cat-quiz",
    description: "Test your knowledge about cats and their behavior",
    language: "EN",
    status: "PUBLIC",
    estimatedDuration: "PT5M",
    thumbnail: null,
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    authorName: "John Doe",
    submissionsCount: 42,
    questionsCount: 10,
    createdAt: "2024-11-15T10:30:00Z",
    updatedAt: "2024-11-15T10:30:00Z",
  },
  {
    id: "2",
    name: "JavaScript Basics",
    slug: "javascript-basics",
    description: "A comprehensive quiz about JavaScript fundamentals",
    language: "EN",
    status: "PUBLIC",
    estimatedDuration: "PT10M",
    thumbnail: null,
    allowsQuestionsPreview: true,
    allowsGuestSubmissions: false,
    saveSubmissions: true,
    authorName: "John Doe",
    submissionsCount: 128,
    questionsCount: 15,
    createdAt: "2024-10-20T14:15:00Z",
    updatedAt: "2024-10-20T14:15:00Z",
  },
  {
    id: "3",
    name: "Customer Satisfaction Survey",
    slug: "customer-satisfaction-survey",
    description: "Help us improve our services by providing feedback",
    language: "EN",
    status: "PUBLIC",
    estimatedDuration: "PT3M",
    thumbnail: null,
    allowsQuestionsPreview: false,
    allowsGuestSubmissions: true,
    saveSubmissions: true,
    authorName: "John Doe",
    submissionsCount: 315,
    questionsCount: 8,
    createdAt: "2024-09-05T08:00:00Z",
    updatedAt: "2024-11-28T16:45:00Z",
  },
];
