name: Build Frontend
run-name: ${{ github.actor }} is building frontend
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Cache Next.js build output
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/pnpm-lock.yaml') }}-${{ hashFiles('frontend/**/*.js', 'frontend/**/*.jsx', 'frontend/**/*.ts', 'frontend/**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Check linting with ESLint
        run: pnpm lint

      - name: Check translations consistency
        run: pnpx @lingual/i18n-check@latest --source en --locales messages

      - name: Build project
        run: pnpm build
