name: Keycloak theme build
run-name: ${{ github.actor }} is building keycloak theme
on:
  pull_request:
    paths:
      - "keycloak/keycloak-theme/**"
      - ".github/workflows/keycloak-theme-build.yaml"

jobs:
  keycloak-theme-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./keycloak/keycloak-theme

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm and node
        uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true
          install: false
          package-json-file: ./keycloak/keycloak-theme/package.json
          cache-dependency-path: ./keycloak/keycloak-theme/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Check linting with ESLint
        run: pnpm lint

      - name: Build project
        run: pnpm keycloakify sync-extensions && pnpm build
